package migration

const version2MaxMigrationWalBytes = 64 * 1024 * 1024

var version2Statements = []string{
	"CREATE TABLE cache_blobs(sha256 TEXT PRIMARY KEY CHECK(length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'), size_bytes INTEGER NOT NULL CHECK(size_bytes >= 0), basename TEXT NOT NULL UNIQUE CHECK(basename = 'blobs/sha256/' || substr(sha256, 1, 2) || '/' || sha256 || '.blob'), state TEXT NOT NULL CHECK(state IN ('published', 'deleting')), created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0), last_access_unix INTEGER NOT NULL CHECK(last_access_unix >= created_at_unix)) STRICT",
	"CREATE TABLE cache_entries(entry_id TEXT PRIMARY KEY CHECK(length(entry_id) = 64 AND entry_id NOT GLOB '*[^0-9a-f]*'), endpoint_id TEXT NOT NULL CHECK(length(endpoint_id) BETWEEN 1 AND 255), path_bytes BLOB NOT NULL CHECK(length(path_bytes) BETWEEN 1 AND 4096), fingerprint_strength TEXT NOT NULL CHECK(fingerprint_strength IN ('weak', 'stat', 'identity', 'strong')), fingerprint_size INTEGER CHECK(fingerprint_size IS NULL OR fingerprint_size >= 0), modified_unix_nano INTEGER, modified_precision TEXT, file_id TEXT, version_id TEXT, hash_algorithm TEXT, hash_hex TEXT, freshness TEXT NOT NULL CHECK(freshness IN ('fresh', 'stale', 'unknown')), policy TEXT NOT NULL CHECK(policy IN ('lru', 'ephemeral', 'pinned_offline')), workspace_id TEXT, pinned INTEGER NOT NULL CHECK(pinned IN (0, 1)), blob_sha256 TEXT REFERENCES cache_blobs(sha256), complete INTEGER NOT NULL CHECK(complete IN (0, 1)), created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0), last_access_unix INTEGER NOT NULL CHECK(last_access_unix >= created_at_unix), CHECK((complete = 1 AND blob_sha256 IS NOT NULL) OR (complete = 0 AND blob_sha256 IS NULL)), CHECK(policy <> 'pinned_offline' OR pinned = 1), CHECK(workspace_id IS NULL OR length(workspace_id) BETWEEN 1 AND 128)) STRICT",
	"CREATE TABLE cache_materializations(materialization_id TEXT PRIMARY KEY CHECK(length(materialization_id) = 32 AND materialization_id NOT GLOB '*[^0-9a-f]*'), entry_id TEXT NOT NULL REFERENCES cache_entries(entry_id), baseline_blob_sha256 TEXT REFERENCES cache_blobs(sha256), basename TEXT NOT NULL UNIQUE CHECK(basename = 'materializations/' || materialization_id || '/content'), size_bytes INTEGER NOT NULL CHECK(size_bytes >= 0), current_sha256 TEXT CHECK(current_sha256 IS NULL OR (length(current_sha256) = 64 AND current_sha256 NOT GLOB '*[^0-9a-f]*')), state TEXT NOT NULL CHECK(state IN ('preparing', 'clean', 'dirty', 'orphaned', 'deleting')), pinned INTEGER NOT NULL CHECK(pinned IN (0, 1)), created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0), updated_at_unix INTEGER NOT NULL CHECK(updated_at_unix >= created_at_unix), last_access_unix INTEGER NOT NULL CHECK(last_access_unix >= created_at_unix), CHECK(state = 'preparing' OR current_sha256 IS NOT NULL)) STRICT",
	"CREATE TABLE cache_references(reference_id TEXT PRIMARY KEY CHECK(length(reference_id) = 32 AND reference_id NOT GLOB '*[^0-9a-f]*'), owner_kind TEXT NOT NULL CHECK(owner_kind IN ('workspace', 'preview', 'edit', 'open', 'upload')), owner_id TEXT NOT NULL CHECK(length(owner_id) BETWEEN 1 AND 128), blob_sha256 TEXT REFERENCES cache_blobs(sha256), materialization_id TEXT REFERENCES cache_materializations(materialization_id), created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0), CHECK((blob_sha256 IS NOT NULL AND materialization_id IS NULL) OR (blob_sha256 IS NULL AND materialization_id IS NOT NULL)), UNIQUE(owner_kind, owner_id, blob_sha256, materialization_id)) STRICT",
	"CREATE TABLE cache_leases(lease_id TEXT PRIMARY KEY CHECK(length(lease_id) = 32 AND lease_id NOT GLOB '*[^0-9a-f]*'), blob_sha256 TEXT REFERENCES cache_blobs(sha256), materialization_id TEXT REFERENCES cache_materializations(materialization_id), owner_kind TEXT NOT NULL CHECK(owner_kind IN ('preview', 'edit', 'open', 'upload')), owner_id TEXT NOT NULL CHECK(length(owner_id) BETWEEN 1 AND 128), daemon_instance_id TEXT NOT NULL CHECK(length(daemon_instance_id) = 32 AND daemon_instance_id NOT GLOB '*[^0-9a-f]*'), owner_pid INTEGER CHECK(owner_pid IS NULL OR owner_pid > 0), process_birth_identity TEXT, heartbeat_at_unix INTEGER NOT NULL CHECK(heartbeat_at_unix > 0), expires_at_unix INTEGER NOT NULL CHECK(expires_at_unix >= heartbeat_at_unix), grace_until_unix INTEGER NOT NULL CHECK(grace_until_unix >= expires_at_unix), state TEXT NOT NULL CHECK(state IN ('active', 'uncertain', 'released')), CHECK((blob_sha256 IS NOT NULL AND materialization_id IS NULL) OR (blob_sha256 IS NULL AND materialization_id IS NOT NULL)), CHECK((owner_pid IS NULL AND process_birth_identity IS NULL) OR (owner_pid IS NOT NULL AND process_birth_identity IS NOT NULL AND length(process_birth_identity) BETWEEN 1 AND 128))) STRICT",
	"CREATE TABLE edit_sessions(session_id TEXT PRIMARY KEY CHECK(length(session_id) = 32 AND session_id NOT GLOB '*[^0-9a-f]*'), source_entry_id TEXT NOT NULL REFERENCES cache_entries(entry_id), materialization_id TEXT NOT NULL UNIQUE REFERENCES cache_materializations(materialization_id), local_state TEXT NOT NULL CHECK(local_state IN ('unknown', 'clean', 'dirty', 'deleted')), remote_state TEXT NOT NULL CHECK(remote_state IN ('unknown', 'unchanged', 'modified', 'deleted', 'unavailable')), state TEXT NOT NULL CHECK(state IN ('preparing', 'editing', 'observing', 'awaiting_decision', 'conflict', 'uploading', 'completed', 'abandoned', 'recovery')), state_version INTEGER NOT NULL CHECK(state_version > 0), created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0), updated_at_unix INTEGER NOT NULL CHECK(updated_at_unix >= created_at_unix)) STRICT",
	"CREATE TABLE edit_session_events(session_id TEXT NOT NULL REFERENCES edit_sessions(session_id), sequence INTEGER NOT NULL CHECK(sequence > 0), event_id TEXT NOT NULL UNIQUE CHECK(length(event_id) BETWEEN 1 AND 128), kind TEXT NOT NULL CHECK(length(kind) BETWEEN 1 AND 64), error_code TEXT, created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0), PRIMARY KEY(session_id, sequence)) STRICT, WITHOUT ROWID",
	"CREATE TABLE edit_session_jobs(session_id TEXT PRIMARY KEY REFERENCES edit_sessions(session_id), job_id TEXT NOT NULL UNIQUE REFERENCES jobs(job_id), created_at_unix INTEGER NOT NULL CHECK(created_at_unix > 0)) STRICT",
	"CREATE INDEX cache_entries_by_lru ON cache_entries(policy, pinned, last_access_unix, entry_id)",
	"CREATE INDEX cache_entries_by_workspace ON cache_entries(workspace_id, policy, last_access_unix, entry_id)",
	"CREATE INDEX cache_materializations_by_recovery ON cache_materializations(state, pinned, last_access_unix, materialization_id)",
	"CREATE INDEX cache_references_by_blob ON cache_references(blob_sha256, reference_id)",
	"CREATE INDEX cache_references_by_materialization ON cache_references(materialization_id, reference_id)",
	"CREATE INDEX cache_leases_by_expiry ON cache_leases(state, grace_until_unix, lease_id)",
	"CREATE INDEX edit_sessions_by_recovery ON edit_sessions(state, updated_at_unix, session_id)",
}

// Version2 adds the daemon-owned Stage 3 cache, lease, and edit-session catalog.
// Version 1 remains byte-for-byte immutable and is always applied first.
func Version2() Migration {
	statements := make([]string, len(version2Statements))
	copy(statements, version2Statements)
	return Migration{
		Version:              2,
		Name:                 "stage3_cache",
		Statements:           statements,
		MaxMigrationWalBytes: version2MaxMigrationWalBytes,
	}
}
