package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/TyrantLucifer/awesome-mac-sftp/internal/releasepack"
)

const (
	materialManifestSchema = "amsftp-third-party-materials-v1"
	maxNoticeInputBytes    = 1 << 20
)

type materialManifest struct {
	Schema  string           `json:"schema"`
	Modules []materialModule `json:"modules"`
}

type materialModule struct {
	Path            string         `json:"path"`
	Version         string         `json:"version"`
	ResolvedPath    string         `json:"resolved_path"`
	ResolvedVersion string         `json:"resolved_version"`
	License         string         `json:"license"`
	Files           []materialFile `json:"files"`
}

type materialFile struct {
	Name   string `json:"name"`
	SHA256 string `json:"sha256"`
}

type listedModule struct {
	Path    string        `json:"Path"`
	Version string        `json:"Version"`
	Dir     string        `json:"Dir"`
	Replace *listedModule `json:"Replace"`
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, stdout io.Writer) error {
	runtimePath, materialsPath, checkPath, err := noticeArguments(args)
	if err != nil {
		return err
	}
	modules, err := readRuntimeModules(runtimePath)
	if err != nil {
		return err
	}
	directories, err := resolveModuleDirectories(modules)
	if err != nil {
		return err
	}
	return renderOrCheckNotice(materialsPath, checkPath, stdout, modules, directories)
}

func runWithModuleDirectories(args []string, stdout io.Writer, directories map[string]string) error {
	runtimePath, materialsPath, checkPath, err := noticeArguments(args)
	if err != nil {
		return err
	}
	modules, err := readRuntimeModules(runtimePath)
	if err != nil {
		return err
	}
	return renderOrCheckNotice(materialsPath, checkPath, stdout, modules, directories)
}

func noticeArguments(args []string) (string, string, string, error) {
	if len(args) == 2 {
		return args[0], args[1], "", nil
	}
	if len(args) == 4 && args[0] == "--check" {
		return args[1], args[2], args[3], nil
	}
	return "", "", "", errors.New("usage: releasenotice [--check] RUNTIME_DEPENDENCIES.json LICENSE_MATERIALS.json [NOTICE]")
}

func renderOrCheckNotice(materialPath, checkPath string, stdout io.Writer, modules []releasepack.Module, directories map[string]string) error {
	var generated bytes.Buffer
	if err := runWithLoadedModules(materialPath, &generated, modules, directories); err != nil {
		return err
	}
	if checkPath == "" {
		_, err := stdout.Write(generated.Bytes())
		return err
	}
	file, err := openBoundedJSON(checkPath)
	if err != nil {
		return fmt.Errorf("check committed third-party notice: %w", err)
	}
	defer file.Close()
	committed, err := io.ReadAll(io.LimitReader(file, maxNoticeInputBytes+1))
	if err != nil {
		return fmt.Errorf("check committed third-party notice: %w", err)
	}
	if !bytes.Equal(committed, generated.Bytes()) {
		return errors.New("check committed third-party notice: generated bytes differ")
	}
	return nil
}

func runWithLoadedModules(materialPath string, stdout io.Writer, modules []releasepack.Module, directories map[string]string) error {
	manifest, err := readMaterialManifest(materialPath)
	if err != nil {
		return err
	}
	materials := make([]releasepack.ModuleNotice, 0, len(manifest.Modules))
	for _, module := range manifest.Modules {
		root, exists := directories[module.ResolvedPath+"@"+module.ResolvedVersion]
		if !exists || root == "" {
			return errors.New("generate third-party notice: resolved module directory is missing")
		}
		files := make([]releasepack.NoticeFile, 0, len(module.Files))
		for _, file := range module.Files {
			raw, err := readModuleLicenseFile(root, file.Name)
			if err != nil {
				return fmt.Errorf("generate third-party notice: load %s@%s %s: %w", module.ResolvedPath, module.ResolvedVersion, file.Name, err)
			}
			files = append(files, releasepack.NoticeFile{Name: file.Name, SHA256: file.SHA256, Bytes: raw})
		}
		materials = append(materials, releasepack.ModuleNotice{
			Path: module.Path, Version: module.Version, ResolvedPath: module.ResolvedPath, ResolvedVersion: module.ResolvedVersion,
			License: module.License, Files: files,
		})
	}
	notice, err := releasepack.BuildThirdPartyNotice(modules, materials)
	if err != nil {
		return err
	}
	_, err = stdout.Write(notice)
	return err
}

func readRuntimeModules(name string) ([]releasepack.Module, error) {
	file, err := openBoundedJSON(name)
	if err != nil {
		return nil, fmt.Errorf("read runtime dependency inventory: %w", err)
	}
	defer file.Close()
	decoder := json.NewDecoder(io.LimitReader(file, maxNoticeInputBytes+1))
	decoder.DisallowUnknownFields()
	var modules []releasepack.Module
	if err := decoder.Decode(&modules); err != nil {
		return nil, fmt.Errorf("read runtime dependency inventory: %w", err)
	}
	if len(modules) == 0 {
		return nil, errors.New("read runtime dependency inventory: modules are missing")
	}
	if err := requireJSONEOF(decoder); err != nil {
		return nil, fmt.Errorf("read runtime dependency inventory: %w", err)
	}
	return modules, nil
}

func readMaterialManifest(name string) (materialManifest, error) {
	file, err := openBoundedJSON(name)
	if err != nil {
		return materialManifest{}, fmt.Errorf("read license material inventory: %w", err)
	}
	defer file.Close()
	decoder := json.NewDecoder(io.LimitReader(file, maxNoticeInputBytes+1))
	decoder.DisallowUnknownFields()
	var manifest materialManifest
	if err := decoder.Decode(&manifest); err != nil {
		return materialManifest{}, fmt.Errorf("read license material inventory: %w", err)
	}
	if err := requireJSONEOF(decoder); err != nil {
		return materialManifest{}, fmt.Errorf("read license material inventory: %w", err)
	}
	if manifest.Schema != materialManifestSchema || len(manifest.Modules) == 0 {
		return materialManifest{}, errors.New("read license material inventory: schema or modules are invalid")
	}
	return manifest, nil
}

func openBoundedJSON(name string) (*os.File, error) {
	info, err := os.Lstat(name) //nolint:gosec // name is the command's explicit local inventory input.
	if err != nil {
		return nil, err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxNoticeInputBytes {
		return nil, errors.New("input must be a bounded non-symlink regular file")
	}
	file, err := os.Open(name) //nolint:gosec // Lstat above validates the explicit input.
	if err != nil {
		return nil, err
	}
	opened, err := file.Stat()
	if err != nil || !opened.Mode().IsRegular() || opened.Size() != info.Size() {
		if closeErr := file.Close(); closeErr != nil {
			return nil, fmt.Errorf("close changed input: %w", closeErr)
		}
		return nil, errors.New("input identity changed while opening")
	}
	return file, nil
}

func requireJSONEOF(decoder *json.Decoder) error {
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return errors.New("trailing JSON is forbidden")
	}
	return nil
}

func resolveModuleDirectories(modules []releasepack.Module) (map[string]string, error) {
	command := exec.Command("go", "list", "-m", "-json", "all") //nolint:gosec // executable and arguments are fixed; no inventory value enters the command.
	output, err := command.Output()
	if err != nil {
		return nil, fmt.Errorf("resolve runtime module directories: %w", err)
	}
	expected := make(map[string]struct{}, len(modules))
	for _, module := range modules {
		pathValue, version := module.Path, module.Version
		if module.Replacement != nil {
			pathValue, version = module.Replacement.Path, module.Replacement.Version
		}
		expected[pathValue+"@"+version] = struct{}{}
	}
	resolved := make(map[string]string, len(expected))
	decoder := json.NewDecoder(bytes.NewReader(output))
	for {
		var module listedModule
		if err := decoder.Decode(&module); errors.Is(err, io.EOF) {
			break
		} else if err != nil {
			return nil, fmt.Errorf("resolve runtime module directories: decode: %w", err)
		}
		pathValue, version, directory := module.Path, module.Version, module.Dir
		if module.Replace != nil {
			pathValue, version, directory = module.Replace.Path, module.Replace.Version, module.Replace.Dir
		}
		key := pathValue + "@" + version
		if _, wanted := expected[key]; wanted && directory != "" {
			resolved[key] = directory
		}
	}
	if len(resolved) != len(expected) {
		return nil, errors.New("resolve runtime module directories: exact resolved inventory is incomplete")
	}
	return resolved, nil
}

func readModuleLicenseFile(root, name string) ([]byte, error) {
	if name == "" || filepath.Base(name) != name || filepath.Clean(name) != name || strings.ContainsAny(name, "\x00\r\n\t ") {
		return nil, errors.New("license source name is invalid")
	}
	resolvedRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		return nil, err
	}
	candidate := filepath.Join(resolvedRoot, name)
	info, err := os.Lstat(candidate) //nolint:gosec // candidate is one canonical base name below the resolved module directory.
	if err != nil {
		return nil, err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxNoticeInputBytes {
		return nil, errors.New("license source must be a bounded non-symlink regular file")
	}
	raw, err := os.ReadFile(candidate) //nolint:gosec // candidate is confined to one validated base name below resolvedRoot.
	if err != nil {
		return nil, err
	}
	if int64(len(raw)) != info.Size() {
		return nil, errors.New("license source identity changed while reading")
	}
	return raw, nil
}
